### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by snehankekre** [snehankekre/streamlit-tensorboard#6]
[streamlit-tensorboard](https://github.com/snehankekre/streamlit-tensorboard/) works on GNU/Linux systems and does not work on Windows. I welcome [PRs](https://github.com/snehankekre/streamlit-tensorboard/pulls) for added Windows support.

**Comment by ansonnn07** [comment]
I am able to run this perfectly on Windows. The Tensorboard shows up fine with the usual graphs. What exactly do you mean by Windows is not supported?

**Comment by snehankekre** [comment]
Windows directories that included `\\` and `\` didn't work, but your PR #9 has fixed this issue. Thank you!! :balloon:
